# Generated by Django 5.0.4 on 2024-04-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doggyWorld_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='precioTotal',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.FloatField(),
        ),
    ]
